// Redux Playground Action Types
export const ADD_COUNTER = "ADD_COUNTER";
export const ADD_HELP = "ADD_HELP";

// Recipe List Search Action Types
export const FETCH_RECIPE_LIST = "FETCH_RECIPE_LIST";
export const FETCH_RECIPE_LIST_SUCCESS = "FETCH_RECIPE_LIST_SUCCESS";
export const FETCH_RECIPE_LIST_ERROR = "FETCH_RECIPE_LIST_ERROR";
export const STORE_RDA = "STORE_RDA";

// Auth Action Types
export const FETCH_USER_AUTH = "FETCH_USER_AUTH";
export const FETCH_USER_AUTH_SUCCESS = "FETCH_USER_AUTH_SUCCESS";
export const FETCH_USER_AUTH_ERROR = "FETCH_USER_AUTH_ERROR";
export const FETCH_PROFILE_PIC = "FETCH_PROFILE_PIC";
export const FETCH_PROFILE_PIC_SUCCESS = "FETCH_PROFILE_PIC_SUCCESS";
export const FETCH_PROFILE_PIC_ERROR = "FETCH_PROFILE_PIC_ERROR";
export const STORE_GENDER = "STORE_GENDER";

// Nutrition Screen Action Types
export const FETCH_USER_JOURNAL = "FETCH_USER_JOURNAL";
export const FETCH_USER_JOURNAL_SUCCESS = "FETCH_USER_JOURNAL_SUCCESS";
export const FETCH_USER_JOURNAL_SUCCESS_BUT_EMPTY =
  "FETCH_USER_JOURNAL_SUCCESS_BUT_EMPTY";
export const FETCH_USER_JOURNAL_ERROR = "FETCH_USER_JOURNAL_ERROR";
export const STORE_DATES = "STORE_DATES";
export const STORE_CALORIES = "STORE_CALORIES";
